apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kardex-sim.fullname" . }}
  labels:
    {{- include "kardex-sim.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kardex-sim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kardex-sim.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: kardex
              containerPort: {{ .Values.kardexsim.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.kardexsim.port }}
            initialDelaySeconds: 45
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: {{ .Values.kardexsim.port }}
            initialDelaySeconds: 120
            periodSeconds: 60

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
