apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "kardex-sim.fullname" .) .Values.service.name }}
  labels: {{- include "kardex-sim.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.kardexsim.port }}
      targetPort: kardex
      protocol: TCP
  selector: {{- include "kardex-sim.selectorLabels" . | nindent 4 }}
