{{- if .Values.certificate.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "odyssey.fullname" . }}
  labels:
    {{- include "odyssey.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
  {{- toYaml .Values.certificate.issuerRef | nindent 4 }}
  dnsNames:
  {{- toYaml .Values.certificate.dnsNames | nindent 4 }}
{{- end }}
