apiVersion: v1
kind: ConfigMap
metadata:
  name: autossh-config-{{- include "autossh.fullname" . }}
data:
  SERVER_ALIVE_COUNT_MAX: {{ .Values.autossh.server_alive_count_max | quote }}
  SSH_BIND_IP: {{ .Values.autossh.ssh_bind_ip | quote }}
  SSH_TUNNEL_PORT: {{ .Values.autossh.ssh_tunnel_port | quote }}
  SSH_MODE: {{ .Values.autossh.ssh_mode | quote }}
  SSH_REMOTE_HOST: {{ .Values.autossh.ssh_remote_host | quote }}
  SSH_REMOTE_PORT: {{ .Values.autossh.ssh_remote_port | quote }}
  SSH_REMOTE_USER: {{ .Values.autossh.ssh_remote_user | quote }}
  SSH_TARGET_HOST: {{ .Values.autossh.ssh_target_host | quote }}
  SSH_TARGET_PORT: {{ .Values.autossh.ssh_target_port | quote }}
