apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "autossh.fullname" .) .Values.service.name }}
  labels:
    {{- include "autossh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "autossh.selectorLabels" . | nindent 4 }}
