---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "py3o.name" . }}
  labels:
    {{- include "py3o.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "py3o.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "py3o.selectorLabels" . | nindent 8 }}
        {{- with .Values.additionalLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: py3orender
          image: "{{ .Values.image.py3orender.repository }}:{{ .Values.image.py3orender.tag }}"
          ports:
            - containerPort: 8994
              name: py3orender
          readinessProbe:
            tcpSocket:
              port: 8994
          livenessProbe:
            tcpSocket:
              port: 8994
          resources:
            {{- toYaml .Values.resources.py3orender | nindent 12 }}

        - name: oooserver
          image: "{{ .Values.image.oooserver.repository }}:{{ .Values.image.oooserver.tag }}"
          ports:
            - containerPort: 8997
              name: oooserver
          readinessProbe:
            tcpSocket:
              port: 8997
          livenessProbe:
            tcpSocket:
              port: 8997
          resources:
            {{- toYaml .Values.resources.oooserver | nindent 12 }}

        - name: py3ofusion
          image: "{{ .Values.image.py3ofusion.repository }}:{{ .Values.image.py3ofusion.tag }}"
          ports:
            - containerPort: 8765
              name: py3ofusion
          readinessProbe:
            tcpSocket:
              port: 8765
          livenessProbe:
            tcpSocket:
              port: 8765
          resources:
            {{- toYaml .Values.resources.py3ofusion | nindent 12 }}


      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "py3o.name" . }}
  labels:
    {{- include "py3o.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8994
      name: py3orender
      targetPort: py3orender
    - port: 8997
      name: oooserver
      targetPort: oooserver
    - port: 8765
      name: py3ofusion
      targetPort: py3ofusion

  selector:
    {{- include "py3o.selectorLabels" . | nindent 4 }}
...
