apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kardex-secret
data:
{{- with .Values.kardex.secrets }}
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | toString | b64enc }}
  {{- end }}
{{- end }}
