apiVersion: v1
kind: ConfigMap
metadata:
  name: kardex-config-{{- include "kardex-proxy.fullname" . }}
data:
  KARDEX_HOST: {{ .Values.kardex.host | quote }}
  KARDEX_port: {{ .Values.kardex.port | default "2001" | quote }}
  KARDEX_TLS: {{ .Values.kardex.tls | default "1" | quote }}
  ODOO_URL: {{ .Values.kardex.odoo_url | default "https://localhost:8069" | quote }}
