apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "kardex-proxy.fullname" .) .Values.service.name }}
  labels: {{- include "kardex-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "kardex-proxy.selectorLabels" . | nindent 4 }}
