{{- with .Values.scannersentinel.secrets }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: scannersentinel-secret
data:
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | toString | b64enc }}
  {{- end }}
{{- end }}
