{{ if .Values.odoo.queuejob.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odooqueue-config
data:
  SERVER_WIDE_MODULES: web,attachment_s3,session_redis,logging_json,queue_job
  WORKERS: {{ .Values.odoo.queuejob.workers | default "2" | quote }}
  LIMIT_MEMORY_SOFT: {{ .Values.odoo.queuejob.limits.soft | default "787973120" | quote }}
  LIMIT_MEMORY_HARD: {{ .Values.odoo.queuejob.limits.hard | default "2147483648" | quote }}
  MAX_CRON_THREADS: {{ .Values.odoo.queuejob.max_cron | default "0" | quote }}
  ODOO_QUEUE_JOB_CHANNELS: {{ .Values.odoo.queuejob.channels | default "root:2" }}
{{ end }}
