---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo.name" . }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "odoo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        config-hash: {{ include (print $.Template.BasePath "/config-odoo.yaml") $ | sha256sum | trunc 63 }}
      labels:
        {{- include "odoo.selectorLabels" . | nindent 8 }}
        {{- with .Values.additionalLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: odoo
          image: "{{ .Values.image.odoo.repository }}:{{ .Values.image.odoo.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.odoo.db.hostSecret.name | quote }}
                  key: {{ .Values.odoo.db.hostSecret.key | quote }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.odoo.db.nameSecret.name | quote }}
                  key: {{ .Values.odoo.db.nameSecret.key | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.odoo.db.userSecret.name | quote }}
                  key: {{ .Values.odoo.db.userSecret.key | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.odoo.db.passwordSecret.name | quote }}
                  key: {{ .Values.odoo.db.passwordSecret.key | quote }}
            - name: DB_PORT
              value: {{ .Values.odoo.db.port | default "5432" | quote }}
            - name: DB_MAXCONN
              value: {{ .Values.odoo.db.max_conn | default "5" | quote }}
            {{- if .Values.odoo.redis.enabled }}
            - name: ODOO_SESSION_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.odoo.redis.hostSecret.name | quote }}
                  key: {{ .Values.odoo.redis.hostSecret.key | quote }}
            - name: ODOO_SESSION_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.odoo.redis.passwordSecret.name | quote }}
                  key: {{ .Values.odoo.redis.passwordSecret.key | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: odoo-config
            - secretRef:
                name: odoo-secret
                optional: true
          ports:
            - containerPort: 8069
              name: odoo
            - containerPort: 8072
              name: longpolling
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.odoo | nindent 12 }}
        - name: nginx
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: nginx-config
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
          ports:
            - containerPort: 80
              name: http
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ if .Values.odoo.queuejob.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo.name" . }}-queuejob
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "odoo.selectorLabels" . | nindent 6 }}
      queuejob: "true"
  template:
    metadata:
      annotations:
        config-hash: {{ include (print $.Template.BasePath "/config-odoo.yaml") $ | sha256sum | trunc 63 }}
      labels:
        {{- include "odoo.selectorLabels" . | nindent 8 }}
        {{- with .Values.additionalLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        queuejob: "true"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: odooqueue
          image: "{{ .Values.image.odoo.repository }}:{{ .Values.image.odoo.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.odoo.db.hostSecret.name | quote }}
                  key: {{ .Values.odoo.db.hostSecret.key | quote }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.odoo.db.nameSecret.name | quote }}
                  key: {{ .Values.odoo.db.nameSecret.key | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.odoo.db.userSecret.name | quote }}
                  key: {{ .Values.odoo.db.userSecret.key | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.odoo.db.passwordSecret.name | quote }}
                  key: {{ .Values.odoo.db.passwordSecret.key | quote }}
            - name: DB_PORT
              value: {{ .Values.odoo.db.port | default "5432" | quote }}
            - name: DB_MAXCONN
              value: {{ .Values.odoo.db.max_conn | default "5" | quote }}
            {{- if .Values.odoo.redis.enabled }}
            - name: ODOO_SESSION_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.odoo.redis.hostSecret.name | quote }}
                  key: {{ .Values.odoo.redis.hostSecret.key | quote }}
            - name: ODOO_SESSION_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.odoo.redis.passwordSecret.name | quote }}
                  key: {{ .Values.odoo.redis.passwordSecret.key | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: odoo-config
            - configMapRef:
                name: odooqueue-config
            - secretRef:
                name: odoo-secret
                optional: true
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.odoo | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo.fullname" . }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    {{- include "odoo.selectorLabels" . | nindent 4 }}
...
