---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: camptocamp-odoo-int
spec:
  type: 0
  resourceID: /subscriptions/ba876afa-17da-448f-ac06-334bfb53b7d5/resourcegroups/odoo-platform-poc/providers/Microsoft.ManagedIdentity/userAssignedIdentities/camptocamp-odoo-int
  clientID: "a8d91d77-4258-4d67-a6aa-47602c140136"
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: azure-pod-identity-binding
spec:
  azureIdentity: camptocamp-odoo-int
  selector: azure-pod-identity-binding-selector
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  secretObjects:
    - secretName: odoo-secret
      type: Opaque
      data:
        - objectName: DB-PASSWORD
          key: DB_PASSWORD
        - objectName: ADMIN-PASSWORD
          key: ADMIN_PASSWORD
        - objectName: AWS-ACCESS-KEY
          key: AWS_ACCESS_KEY_ID
        - objectName: AWS-SECRET-KEY
          key: AWS_SECRET_ACCESS_KEY
  parameters:
    usePodIdentity: "true"
    keyvaultName: camptocamp-odoo-int
    objects:  |
      array:
        - |
          objectName: DB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: ADMIN-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: AWS-ACCESS-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: AWS-SECRET-KEY
          objectType: secret
          objectVersion: ""
    tenantId: "4ec7b0fa-1945-4bb2-8a25-f7d22c6fdde4"
...
