# Default values for kwkhtmltopdf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  kwkhtmltopdf:
    repository: acsone/kwkhtmltopdf
    tag: 0.12.1.3-latest

services:
  kwkhtmltopdf:
    targetPort: 8080

resources:
  kwkhtmltopdf:
    requests:
      cpu: 125m
      memory: 128Mi
      ephemeral-storage: "2Gi"
    limits:
      cpu: 500m
      memory: 8Gi
      ephemeral-storage: "4Gi"
nodeSelector: {}
tolerations: []
affinity: {}

additionalLabels: {}
  # aadpodidbinding: some-identity
#no_storage_cleaning: true
volumeMounts:
  - name: kwkhtmltopdftmp
    mountPath: /tmp

volumes:
  - name: kwkhtmltopdftmp
    emptyDir: {}
