# Default values for py3o.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  py3o:
    repository: xcgd/py3o
    tag: 1.0.0

services:
  py3o:
    targetPort: 8765

resources:
  py3o:
    requests:
      cpu: 0.5
      memory: 256Mi
    limits:
      memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}

additionalLabels: {}
  # aadpodidbinding: some-identity

