apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: celebrimbor-secret
data:
  CLUSTERS: {{ toJson .Values.celebrimbor.clusters | b64enc }}
{{- with .Values.celebrimbor.secrets }}
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | toString | b64enc }}
  {{- end }}
{{- end }}
