{{- if .Values.celebrimbor.key_backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: key-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      backoffLimit: 1
      template:
        metadata:
          labels:
            {{- with .Values.additionalLabels }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          containers:
          - name: key-backup
            image: "{{ .Values.image.key_backup.repository }}:{{ .Values.image.key_backup.tag }}"
            imagePullPolicy: Always
            env:
              - name: GPG_KEYVAULT_NAME
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.celebrimbor.gpg.secret_name }}
                    key: {{ .Values.celebrimbor.gpg.vault_name_key }}
              - name: GPG_KEYVAULT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.celebrimbor.gpg.secret_name }}
                    key: {{ .Values.celebrimbor.gpg.secret_name_key }}
            envFrom:
              - secretRef:
                  name: keybackup-secret
{{ end }}
