---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "celebrimbor.name" . }}
  labels:
    {{- include "celebrimbor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "celebrimbor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        config-hash: {{ include (print $.Template.BasePath "/config-celebrimbor.yaml") $ | sha256sum | trunc 63 }}
        secret-hash: {{ include (print $.Template.BasePath "/config-celebrimbor-secret.yaml") $ | sha256sum | trunc 63 }}
        {{- with .Values.additionalAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "celebrimbor.selectorLabels" . | nindent 8 }}
        {{- with .Values.additionalLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: celebrimbor
          image: "{{ .Values.image.celebrimbor.repository }}:{{ .Values.image.celebrimbor.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AZURE_ACCOUNT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celebrimbor.storage.secret_name }}
                  key: {{ .Values.celebrimbor.storage.account_url_key }}
            - name: AZURE_STORAGE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celebrimbor.storage.secret_name }}
                  key: {{ .Values.celebrimbor.storage.storage_name_key }}
            - name: GPG_KEYVAULT_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celebrimbor.gpg.secret_name }}
                  key: {{ .Values.celebrimbor.gpg.vault_name_key }}
            - name: GPG_KEYVAULT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celebrimbor.gpg.secret_name }}
                  key: {{ .Values.celebrimbor.gpg.secret_name_key }}
            - name: GPG_RECIPIENTS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celebrimbor.gpg.secret_name }}
                  key: {{ .Values.celebrimbor.gpg.recipients_key }}
            - name: SESSION_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celebrimbor.redis.secret_name }}
                  key: {{ .Values.celebrimbor.redis.primary_connection_url_key }}
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celebrimbor.azure_app.secret_name }}
                  key: {{ .Values.celebrimbor.azure_app.client_id_key }}
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celebrimbor.azure_app.secret_name }}
                  key: {{ .Values.celebrimbor.azure_app.client_secret_key }}
            - name: TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celebrimbor.azure_app.secret_name }}
                  key: {{ .Values.celebrimbor.azure_app.tenant_id_key }}
          envFrom:
            - configMapRef:
                name: celebrimbor-config
            - secretRef:
                name: celebrimbor-secret
          ports:
            - containerPort: 5000
              name: celebrimbor
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.celebrimbor | nindent 12 }}
        - name: nginx
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: nginx-config
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
          ports:
            - containerPort: 80
              name: http
        - name: curl-proxy
          image: "{{ .Values.image.curl_proxy.repository }}:{{ .Values.image.curl_proxy.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CELEB_SVC
              value: "localhost"
            - name: CELEB_PORT
              value: "80"
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celebrimbor.azure_app.secret_name }}
                  key: {{ .Values.celebrimbor.azure_app.client_id_key }}
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celebrimbor.azure_app.secret_name }}
                  key: {{ .Values.celebrimbor.azure_app.client_secret_key }}
            - name: TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.celebrimbor.azure_app.secret_name }}
                  key: {{ .Values.celebrimbor.azure_app.tenant_id_key }}
          envFrom:
            - secretRef:
                name: celebrimbor-secret
          resources:
            {{- toYaml .Values.resources.curl_proxy | nindent 12 }}
          ports:
            - containerPort: 8080
              name: curl-http
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "celebrimbor.fullname" . }}
  labels:
    {{- include "celebrimbor.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
      name: http
    - port: 8080
      targetPort: curl-http
      name: curl-http
  selector:
    {{- include "celebrimbor.selectorLabels" . | nindent 4 }}
...
